language: ruby
bundler_args: "--without production --without development"
rvm:
  - 2.2.0
script:
  - bundle exec rake db:migrate test
before_script:
  - psql -c 'create database backstage_test' -U postgres

