production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
staging:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
test:
  secret_key_base: 7cfbfec2439bdca820c82f91b3834adfdd0e9e5937d194aa9f6be7cf03f346e9fe9295e5886b55f22c2dddadac33baa997596bc9797f2d3679f75fa61c5f3b9c
